[build]
command = "npm run build"

[build.upload]
format = "directory"

[site]
bucket = "./dist"

[env.production]
name = "cleanernow"

# Cloudflare Pages specific configuration
[pages]
framework = "vite"
pages_build_output_dir = "dist"
