name = "cleanernow"
compatibility_date = "2024-01-20"

[build]
command = "npm run build"
output_directory = "dist"

[site]
bucket = "./dist"

# Required for Cloudflare Pages
pages_build_output_dir = "dist"
